ip: 192.168.10.10
s3:   
  access_key: "AKIAIPRNHSWEQNWHLCDQ"   
  secret_key: "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"
  bucket: "foggy-project-dhj6" 
synced_folder:   
  host_path: "./magento2/"
  guest_path: "/magento2/" 
mysql:   
  host: "127.0.0.1"   
  username: root
  password: user123
http_basic:   
  repo_magento_com:     
    username: 19c8a6aab812f5eeb401cc5841c035c9    
    password: f227f194505629ba4a809df313a3f9ac
github_oauth:   
  github_com: "2932db7451354af11eca2c69229758f084ea8f0c" 
magento:   
  db_name: "magento"
  admin_firstname: "John"
  admin_lastname: "Doe"
  admin_password: "admin123"
  admin_user: "admin"
  admin_email: "admin@gmail.com"
  backend_frontname: "admin"
  language: "en_US"
  currency: "USD"
  timezone: "Europe/London"
  base_url: "http://192.168.10.10/magento2/"
  fixture: "small"
github:
  repository: "https://github.com/Fr4nks/Magento.git"

